### ISSUE TITLE
[T0687-DX] The format function is not needed in a GSS example

### ISSUE THREAD

**Issue by g-despot** [memgraph/docs#371]
The function `Format()` is not needed in [this example](https://memgraph.com/docs/memgraph-lab/graph-style-script-language#setting-graph-labels):
```cypher
@NodeStyle HasLabel?(node, "Country") {
  label: Format(Property(node, "name"))
}
```

**Comment by kgolubic** [comment]
I've created a new branch with the proposed fix.
