### ISSUE TITLE
[BUG] Potentially wrong use of BFS in reference guide

### ISSUE THREAD

**Issue by brunos252** [memgraph/docs#389]
https://github.com/memgraph/docs/blob/master/docs/reference-guide/graph-algorithms.md

Here, under Breadth First Search, under code:
`MATCH (a {id: 723})-[edge_list:Type *bfs..10]-(b {id: 882}) RETURN *;`
it says:
"The above query will find all paths of length up to 10 between nodes a and b"
and then goes on:
To find only the shortest path, simply append LIMIT 1 to the RETURN clause.
`MATCH (a {id: 723})-[edge_list:Type *bfs..10]-(b {id: 882}) RETURN * LIMIT 1;`

The Issue (I think) is:
BFS always returns only the shortest path, and LIMIT 1 has no effect there.

**Comment by vpavicic** [comment]
This will be fixed this week :)
