### ISSUE TITLE
Update direct download links

### ISSUE THREAD

**Issue by kgolubic** [memgraph/docs#558]
Memgraph 2.4 is out so we need to update links on this page - https://memgraph.com/docs/memgraph/installation/direct-download-links.

**Comment by vpavicic** [comment]
Where does this even exist, how do i get to this?

**Comment by kgolubic** [comment]
You need to check [https://memgraph.com/download](https://memgraph.com/download) to see what is available but as a general rule only the version number changes in the path (directory and filename). I'll assign this one to myself.
