### ISSUE TITLE
Provide link between specific algorithm's docs on MAGE

### ISSUE THREAD

**Issue by antoniofilipovic** [memgraph/docs#575]
One algorithm has multiple description points on MAGE docs. One is under `...docs/mage/query-modules/cpp/X` and other part is on 
`.../docs/mage/algorithms/traditional-graph-analytics/X`. Provide links from one to the other since no such link exists.

@vpavicic check if I described the issue correctly, and update if necessary

**Comment by vpavicic** [comment]
This will be an issue of revamping the MAGE algos pages... 
I will open a new issue for this
