### ISSUE TITLE
Add RETURN statements in MAGE procedures

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/docs#624]
Add `RETURN` after `YIELD` for each of the MAGE procedure code examples. Example: 
[Weakly connected components ](https://memgraph.com/docs/mage/query-modules/cpp/weakly-connected-components#get)

```
CALL weakly_connected_components.get()
YIELD node, component_id;
```

An example case of when the above is not working (on Pandora dataset):

```
MATCH p=(e:Entity)-[:JURISDICTION_IN]->(:Country)
WHERE e.icij_id="7A15CC81D9DA787D79F94E5487CC47C9"
WITH project(p) as subgraph
CALL weakly_connected_components.get(subgraph)
YIELD node, component_id;
```
`Error message: Query should either create or update something, or return results!`

If the above is changed to:

```
MATCH p=(e:Entity)-[:JURISDICTION_IN]->(:Country)
WHERE e.icij_id="7A15CC81D9DA787D79F94E5487CC47C9"
WITH project(p) as subgraph
CALL weakly_connected_components.get(subgraph)
YIELD node, component_id
RETURN node, component_id;
```
then it works.

Hence, the code snippet in docs needs to change to:

```
CALL weakly_connected_components.get()
YIELD node, component_id
RETURN node, component_id;
```

**Comment by vpavicic** [comment]
@Josipmrden - have you resolved this issue?

**Comment by Josipmrden** [comment]
Yes

**Comment by Josipmrden** [comment]
Issue closed with https://github.com/memgraph/docs/pull/619
