### ISSUE TITLE
Add context/hint how to improve CSV load speeds. 

### ISSUE THREAD

**Issue by antejavor** [memgraph/docs#638]
CSV load can go slow if you do not set up the index for MATCH/MERGE on nodes properties, we should consider adding hints about indexes in LOAD CSV docs.  Consider Antonio recommendation on issue: https://github.com/memgraph/memgraph/issues/684#issuecomment-1339677291
There were some similar issues on discord: https://discord.com/channels/842007348272169002/890969266600423504/1050748252078735410

**Comment by vpavicic** [comment]
Kate's comment: We should emphasize indexing more on our LOAD CSV import page. For example, too slow? Try indexing -> link to that.

Duplicated issue: https://github.com/memgraph/docs/issues/678
