### ISSUE TITLE
Revamp import/export section

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/docs#677]
I will expand on this, but for now, it would be great to have a 'best practices' page in the import section. We should explain to the users what is the best way to import their files depending on the dataset scale, etc.

Maybe add migration part too: https://discord.com/channels/842007348272169002/1088748179253624853/1089905564257091635
Include analytics mode, csv import tool, mgconsole batch, load csv, json,..

**Comment by vpavicic** [comment]
Renamig this to Revamp import/export
