### ISSUE TITLE
Expand storage memory usage guide

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/docs#766]
Expand the [storage memory usage reference guide](https://memgraph.com/docs/memgraph/under-the-hood/storage) with info on how to calculate RAM usage for labels. Should the user use additional labels or add an additional string property? A user reported that it was better to use an extra label.  Ante took a quick look into the code base, and the additional label should add 8B of memory usage per node.

**Comment by katarinasupe** [comment]
So fast, so fast. @vpavicic

**Comment by vpavicic** [comment]
CI/CD :D
