### ISSUE TITLE
Content table should be a bullet list

### ISSUE THREAD

**Issue by vpavicic** [memgraph/docs#774]
This bullet list has transformed into a content table
https://memgraph.com/docs/memgraph/import-data/files/cypherl#importing-via-mgconsole

![image](https://user-images.githubusercontent.com/95473291/224695417-8baffda3-d1a5-40d0-8752-775b79ad0b59.png)

**Comment by vpavicic** [comment]
Kruno, could you please check if this is OK? If it is, could you please close the issue, if it isn't can you please fix it?

**Comment by kgolubic** [comment]
It all looks ok to me. I'll close the issue.
