### ISSUE TITLE
Fix a bug on System Requirements

### ISSUE THREAD

**Issue by gitbuda** [memgraph/docs#792]
1. The `System Requirements` part is not indexed under Algoila -> https://memgraph.com/docs/search?q=system%20requirements. I think the reason is because that part is implemented as a React component?

**Comment by vpavicic** [comment]
It's an mdx file, i need to see if I can do anything about it... I'll split this issue into 2 BCS the 2nd one i can do right away

**Comment by vpavicic** [comment]
This is no longer an issue... there was a bug with the angola crawlers
