### ISSUE TITLE
Privileges - check consistency and consider making changes easier

### ISSUE THREAD

**Issue by vpavicic** [memgraph/docs#805]
In this PR we are creating a new privilege `TRANSACTION_MANAGEMENT`.

https://github.com/memgraph/docs/pull/798

![image](https://user-images.githubusercontent.com/95473291/229047302-1ec5116a-63cb-477c-9441-4391e6003d9e.png)

I believe that all three how to guides on enterprise features list the privileges 

https://memgraph.com/docs/memgraph/next/how-to-guides/manage-users-using-ldap

We need to check if all privileges are listed in all places, if not add the ones that are missing - you can add that to the PR #798 

Also, maybe create a template list we can insert to ease up changes? This could be a new PR?

**Comment by kgolubic** [comment]
@vpavicic the info is where it needs to be. I would just test the output of `SHOW PRIVILEGES FOR admin;` in the Memgraph 2.7 and update [the table with the output](https://memgraph.com/docs/memgraph/how-to-guides/manage-label-based-access-control) for that command if needed.
