### ISSUE TITLE
Fix this typo

### ISSUE THREAD

**Issue by vpavicic** [memgraph/docs#857]
![image](https://user-images.githubusercontent.com/95473291/235677689-7d0af9f5-e6f0-45d6-9792-e1f183c52a45.png)

https://memgraph.com/docs/gqlalchemy/import-data

**Comment by kgolubic** [comment]
Can you please update the name of the node from `node2 `to `node1 `at https://memgraph.com/docs/cypher-manual/import-data?

![image](https://user-images.githubusercontent.com/46486712/235691892-00793942-ae20-48b4-b64d-6b1128c2f3ac.png)
