### ISSUE TITLE
Changing streams transform module is fragile. 

### ISSUE THREAD

**Issue by mattang-stang** [memgraph/docs#941]
When I change the default python transformation module, I can't get the changes to actually load. When running tests the changes don't take effect. Furthermore, if there is an syntax error in the python code I get an error "Transformation function XYZ cannot be found".

The file is in the Docker container location where Memgraph originally created it.

![error_1](https://github.com/memgraph/docs/assets/96044240/7a19836d-edfa-4feb-8a3a-8e212d0d18b2)

I am using the following docker image: memgraph/memgraph-platform:2.8.0-memgraph2.8.0-lab2.6.0

**Comment by vpavicic** [comment]
I see you asked the question on Discord so @katarinasupe will continue the conversation there! :)
I'll close the issue as ATM it's not a docs repo issue
