### ISSUE TITLE
Different file and id names

### ISSUE THREAD

**Issue by vpavicic** [memgraph/docs#952]
The two files are called  graphstyle-directive i graphstyle-map-directive, but the ids are viewstyle-directive and viewstyle-map-directive which makes more sense...

What are the implications of renaming these files? Can it be done without breaking anything?

![image](https://github.com/memgraph/docs/assets/95473291/6bc4a379-0014-4f6d-86d6-ae7f115080a6)

**Comment by kgolubic** [comment]
It shouldn't be a problem. I'll update any links that need to be updated.
