### ISSUE TITLE
Add support for Bolt v5 in docs

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/docs#974]
Add that we support Bolt v5, besides v1 and v4 where needed. For example, here: https://memgraph.com/docs/memgraph/next/connect-to-memgraph/drivers

**Comment by aroramrinaal** [comment]
Hey @katarinasupe 
I'm excited to contribute to the project! I'd love to take up the issue of adding support for Bolt v5. My approach would involve thoroughly reviewing the documentation and identifying instances similar to the example you provided at [link to the example](https://github.com/memgraph/docs/blob/master/docs/connect-to-memgraph/drivers/overview.md). I'll ensure to update these instances by adding that the project now supports Bolt v5 alongside v1 and v4 where needed.

Looking forward to working on this!

**Comment by vpavicic** [comment]
Dear @aroramrinaal , thank you so much for your passion, but at the moment, we are restructuring and migrating documentation which will close this issue and archive this repo! :) But be sure to check the new documentation repo, and maybe some issues will call your name again :)
